spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        # trace: true
        web-allow-others: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:


server:
  port: 8080